 # schema.yml

 version: 2

 sources:
   - name: raw  # alias for your BigQuery dataset "gz_raw_data"
     schema: gz_raw_data
     tables: 
       - name: sales # alias for raw_gz_sales
         identifier: raw_gz_sales
       - name: product  # alias for raw_gz_product
         identifier: raw_gz_product
       - name: ship  # alias for raw_gz_ship
         identifier: raw_gz_ship